ALTER TABLE "EmailTemplateReview" ADD COLUMN "copyOverride" JSONB;

INSERT INTO "EmailTemplateReview" (
  "id", "template", "revision", "approvedAt", "approvedById", "approvedByEmail", "createdAt", "updatedAt"
)
SELECT
  'email-default-' || lower("template"),
  "template",
  '2026-07-27-v1',
  CURRENT_TIMESTAMP,
  'SYSTEM',
  'melissa@rhyzefit.com',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
FROM (VALUES
  ('WELCOME'), ('PASSWORD_RESET'), ('NEW_SIGNUP_ADMIN'),
  ('BOOKING_CONFIRMATION'), ('CLASS_REMINDER'), ('BOOKING_CANCELLATION'),
  ('BOOKING_TRANSFERRED'), ('WAITLIST_JOINED'), ('WAITLIST_PROMOTED'),
  ('CLASS_UPDATE'), ('CLASS_CANCELLED'),
  ('MEMBERSHIP_PURCHASE_CONFIRMATION'), ('PURCHASE_CONFIRMATION'),
  ('EVENT_PURCHASE_CONFIRMATION'), ('PAYMENT_RECEIPT'), ('MEMBERSHIP_RENEWED'),
  ('PAYMENT_FAILED'), ('TRIAL_ENDING'), ('MEMBERSHIP_PAUSED'),
  ('MEMBERSHIP_RESUMED'), ('MEMBERSHIP_CANCELLED'), ('NEW_PURCHASE_ADMIN'),
  ('INSTRUCTOR_APPROVAL_NEEDED'), ('INSTRUCTOR_APPROVED'), ('INSTRUCTOR_DENIED'),
  ('INSTRUCTOR_DOCUMENTS_MISSING'), ('CREDENTIAL_VALID'), ('CREDENTIAL_REJECTED'),
  ('CREDENTIAL_EXPIRING'), ('CREDENTIAL_EXPIRED'),
  ('WAIVER_REMINDER_24_HOUR'), ('WAIVER_REMINDER_UPCOMING_CLASS'),
  ('ADMIN_MESSAGE'), ('MEMBER_REPLY'), ('CAMPAIGN'), ('CONTACT_FORM'),
  ('CONTACT_CONFIRMATION')
) AS approved("template")
ON CONFLICT ("template") DO UPDATE SET
  "revision" = EXCLUDED."revision",
  "approvedAt" = EXCLUDED."approvedAt",
  "approvedById" = EXCLUDED."approvedById",
  "approvedByEmail" = EXCLUDED."approvedByEmail",
  "updatedAt" = EXCLUDED."updatedAt";
