export const versionLabel = 'Rhyze Fitness';

export const weekDays = [
  {
    id: 'sun',
    day: 'Sunday',
    shortDay: 'Sun',
    date: 'Aug 2',
    label: 'Sunday, August 2nd',
  },
  {
    id: 'mon',
    day: 'Monday',
    shortDay: 'Mon',
    date: 'Aug 3',
    label: 'Monday, August 3rd',
  },
  {
    id: 'tue',
    day: 'Tuesday',
    shortDay: 'Tue',
    date: 'Aug 4',
    label: 'Tuesday, August 4th',
  },
  {
    id: 'wed',
    day: 'Wednesday',
    shortDay: 'Wed',
    date: 'Aug 5',
    label: 'Wednesday, August 5th',
  },
  {
    id: 'thu',
    day: 'Thursday',
    shortDay: 'Thu',
    date: 'Aug 6',
    label: 'Thursday, August 6th',
  },
  {
    id: 'fri',
    day: 'Friday',
    shortDay: 'Fri',
    date: 'Aug 7',
    label: 'Friday, August 7th',
  },
  {
    id: 'sat',
    day: 'Saturday',
    shortDay: 'Sat',
    date: 'Aug 8',
    label: 'Saturday, August 8th',
  },
] as const;

export const ownedSchedule = [
  {
    id: 'mon-pilates',
    day: 'Mon',
    date: 'Aug 3',
    time: '10:00 AM',
    classSlug: 'pilates-pulse-adrianna',
    className: 'Pilates Pulse with Adrianna',
    instructor: 'Adrianna Jones',
    photo: '/founders/instructor-adriana.jpg',
    room: 'Studio B',
    duration: '50 min',
    capacity: 25,
    booked: 2,
    waitlist: 0,
    price: '$25',
    bookingHref: '/book/pilates-pulse-adrianna',
  },
  {
    id: 'mon-yoga',
    day: 'Mon',
    date: 'Aug 3',
    time: '11:00 AM',
    classSlug: 'yoga-flow-adrianna',
    className: 'Flow with Adrianna',
    instructor: 'Adrianna Jones',
    photo: '/founders/instructor-adriana.jpg',
    room: 'Studio B',
    duration: '50 min',
    capacity: 25,
    booked: 0,
    waitlist: 0,
    price: '$25',
    bookingHref: '/book/yoga-flow-adrianna',
  },
  {
    id: 'mon-ignite',
    day: 'Mon',
    date: 'Aug 3',
    time: '12:00 PM',
    classSlug: 'ignite-julie',
    className: 'Ignite with Julie',
    instructor: 'Julie Reese',
    photo: '/founders/instructor-julie.jpg',
    room: 'Main Floor',
    duration: '50 min',
    capacity: 25,
    booked: 1,
    waitlist: 0,
    price: '$25',
    bookingHref: '/book/ignite-julie',
  },
  {
    id: 'mon-heels-101',
    day: 'Mon',
    date: 'Aug 3',
    time: '6:10 PM',
    classSlug: 'heels-101-walk-with-me-nicole',
    className: 'Heels 101 "Walk with Me" with Nicole',
    instructor: 'Nicole Finley',
    photo: '/founders/instructor-nicole-finley.png',
    room: 'Main Floor',
    duration: '50 min',
    capacity: 25,
    booked: 2,
    waitlist: 0,
    price: '$25',
    bookingHref: '/book/heels-101-walk-with-me-nicole',
  },
  {
    id: 'tue-yoga',
    day: 'Tue',
    date: 'Aug 4',
    time: '8:00 AM',
    classSlug: 'yoga-vinyasa-mackenzie',
    className: 'Vinyasa/Hatha Yoga with Kenzie',
    instructor: 'Mackenzie Heffernan',
    photo: '/founders/instructor-mackenzie-heffernan.jpg',
    room: 'Main Floor',
    duration: '50 min',
    capacity: 25,
    booked: 0,
    waitlist: 0,
    price: '$25',
    bookingHref: '/book/yoga-vinyasa-mackenzie',
  },
  {
    id: 'tue-global-flow',
    day: 'Tue',
    date: 'Aug 4',
    time: '9:10 AM',
    classSlug: 'global-hiit-mackenzie',
    className: 'Global Fit & Flow with Kenzie',
    instructor: 'Mackenzie Heffernan',
    photo: '/founders/instructor-mackenzie-heffernan.jpg',
    room: 'Main Floor',
    duration: '50 min',
    capacity: 25,
    booked: 0,
    waitlist: 0,
    price: '$25',
    bookingHref: '/book/global-hiit-mackenzie',
  },
  {
    id: 'tue-ritmo',
    day: 'Tue',
    date: 'Aug 4',
    time: '11:00 AM',
    classSlug: 'rhyze-ritmo-melissa',
    className: 'Rhyze Ritmo with Melissa',
    instructor: 'Melissa Llanos',
    photo: '/founders/instructor-melissa.jpg',
    room: 'Main Floor',
    duration: '50 min',
    capacity: 25,
    booked: 1,
    waitlist: 0,
    price: '$25',
    bookingHref: '/book/rhyze-ritmo-melissa',
  },
  {
    id: 'tue-soul-line',
    day: 'Tue',
    date: 'Aug 4',
    time: '6:00 PM',
    classSlug: 'soul-line-dancing-rachel',
    className: 'Soul Line & Groove with Rachel',
    instructor: 'Rachel',
    photo: '/founders/instructor-rachel.jpg',
    room: 'Main Floor',
    duration: '50 min',
    capacity: 25,
    booked: 0,
    waitlist: 0,
    price: '$25',
    bookingHref: '/book/soul-line-dancing-rachel',
  },
  {
    id: 'tue-rhyze-up',
    day: 'Tue',
    date: 'Aug 4',
    time: '7:10 PM',
    classSlug: 'rhyze-up-vanessa',
    className: 'Rhyze Up with Vanessa',
    instructor: 'Vanessa Ramos',
    photo: '/founders/instructor-vanessa.jpg',
    room: 'Main Floor',
    duration: '50 min',
    capacity: 25,
    booked: 0,
    waitlist: 0,
    price: '$25',
    bookingHref: '/book/rhyze-up-vanessa',
  },
  {
    id: 'wed-pilates',
    day: 'Wed',
    date: 'Aug 5',
    time: '10:00 AM',
    classSlug: 'pilates-pulse-adrianna',
    className: 'Pilates Pulse with Adrianna',
    instructor: 'Adrianna Jones',
    photo: '/founders/instructor-adriana.jpg',
    room: 'Studio B',
    duration: '50 min',
    capacity: 25,
    booked: 0,
    waitlist: 0,
    price: '$25',
    bookingHref: '/book/pilates-pulse-adrianna',
  },
  {
    id: 'wed-yoga',
    day: 'Wed',
    date: 'Aug 5',
    time: '11:00 AM',
    classSlug: 'yoga-flow-adrianna',
    className: 'Flow with Adrianna',
    instructor: 'Adrianna Jones',
    photo: '/founders/instructor-adriana.jpg',
    room: 'Studio B',
    duration: '50 min',
    capacity: 25,
    booked: 0,
    waitlist: 0,
    price: '$25',
    bookingHref: '/book/yoga-flow-adrianna',
  },
  {
    id: 'wed-ignite',
    day: 'Wed',
    date: 'Aug 5',
    time: '12:00 PM',
    classSlug: 'ignite-julie',
    className: 'Ignite with Julie',
    instructor: 'Julie Reese',
    photo: '/founders/instructor-julie.jpg',
    room: 'Main Floor',
    duration: '50 min',
    capacity: 25,
    booked: 0,
    waitlist: 0,
    price: '$25',
    bookingHref: '/book/ignite-julie',
  },
  {
    id: 'wed-core',
    day: 'Wed',
    date: 'Aug 5',
    time: '5:00 PM',
    classSlug: 'core-360-carla-rio',
    className: 'Core 360 with Carla',
    instructor: 'Carla Hotrock',
    photo: '/founders/instructor-carla.jpg',
    room: 'Main Floor',
    duration: '50 min',
    capacity: 25,
    booked: 0,
    waitlist: 0,
    price: '$25',
    bookingHref: '/book/core-360-carla-rio',
  },
  {
    id: 'wed-grind',
    day: 'Wed',
    date: 'Aug 5',
    time: '6:00 PM',
    classSlug: 'grind-and-grow-carla-reo',
    className: 'Grind & Grow with Carla',
    instructor: 'Carla Hotrock',
    photo: '/founders/instructor-carla.jpg',
    room: 'Main Floor',
    duration: '50 min',
    capacity: 25,
    booked: 0,
    waitlist: 0,
    price: '$25',
    bookingHref: '/book/grind-and-grow-carla-reo',
  },
  {
    id: 'wed-real-riddim',
    day: 'Wed',
    date: 'Aug 5',
    time: '7:10 PM',
    classSlug: 'real-riddim-dance-workout-vanessa',
    className: 'Real Riddim Dance Workout with Vanessa',
    instructor: 'Vanessa Ramos',
    photo: '/founders/instructor-vanessa.jpg',
    room: 'Main Floor',
    duration: '50 min',
    capacity: 25,
    booked: 3,
    waitlist: 0,
    price: '$25',
    bookingHref: '/book/real-riddim-dance-workout-vanessa',
  },
  {
    id: 'thu-ritmo',
    day: 'Thu',
    date: 'Aug 6',
    time: '11:00 AM',
    classSlug: 'rhyze-ritmo-melissa',
    className: 'Rhyze Ritmo with Melissa',
    instructor: 'Melissa Llanos',
    photo: '/founders/instructor-melissa.jpg',
    room: 'Main Floor',
    duration: '50 min',
    capacity: 25,
    booked: 0,
    waitlist: 0,
    price: '$25',
    bookingHref: '/book/rhyze-ritmo-melissa',
  },
  {
    id: 'thu-rhyze-up',
    day: 'Thu',
    date: 'Aug 6',
    time: '7:10 PM',
    classSlug: 'rhyze-up-vanessa',
    className: 'Rhyze Up with Vanessa',
    instructor: 'Vanessa Ramos',
    photo: '/founders/instructor-vanessa.jpg',
    room: 'Main Floor',
    duration: '50 min',
    capacity: 25,
    booked: 0,
    waitlist: 0,
    price: '$25',
    bookingHref: '/book/rhyze-up-vanessa',
  },
  {
    id: 'fri-ignite',
    day: 'Fri',
    date: 'Aug 7',
    time: '12:00 PM',
    classSlug: 'ignite-julie',
    className: 'Ignite with Julie',
    instructor: 'Julie Reese',
    photo: '/founders/instructor-julie.jpg',
    room: 'Main Floor',
    duration: '50 min',
    capacity: 25,
    booked: 0,
    waitlist: 0,
    price: '$25',
    bookingHref: '/book/ignite-julie',
  },
  {
    id: 'sun-yoga',
    day: 'Sun',
    date: 'Aug 9',
    time: '9:00 AM',
    classSlug: 'yoga-vinyasa-mackenzie',
    className: 'Vinyasa/Hatha Yoga with Kenzie',
    instructor: 'Mackenzie Heffernan',
    photo: '/founders/instructor-mackenzie-heffernan.jpg',
    room: 'Main Floor',
    duration: '50 min',
    capacity: 25,
    booked: 1,
    waitlist: 0,
    price: '$25',
    bookingHref: '/book/yoga-vinyasa-mackenzie',
  },
] as const;

export const ownedMemberships = [
  {
    id: 'intro-offer',
    name: 'Intro Offer 7-Days',
    price: '$7',
    cadence: '/ 7 credits',
    eyebrow: '7-day unlimited trial',
    popular: false,
    credits: 'Unlimited standard classes for 7 consecutive days',
    blurb:
      'First-timers get a full week to try dance, yoga, Pilates, strength, and HIIT once they book their first class.',
    perks: ['First-timers only', 'General waiver required', 'No commitment'],
    details: [
      'Activates when first class is booked',
      'Expires automatically 7 days after first booked class',
      'Unlimited standard classes during the trial window',
      'Specialty events and workshops excluded',
      'First-time clients only',
    ],
    href: '/join?plan=intro-offer',
  },
  {
    id: 'full-rhythm',
    name: 'Ritual',
    price: '$168',
    cadence: '/ month',
    eyebrow: '8 classes / month',
    popular: true,
    credits: '8 monthly standard class credits',
    blurb:
      'Includes 8 standard classes per billing cycle at $21 per class, auto-renews monthly, excludes premium specialty events and workshops, and includes a unique 15% merch promo code.',
    perks: [
      'Most popular',
      '15% member merch promo code',
      'Credits do not roll over',
    ],
    details: [
      'Billing begins August 3, 2026 for opening month',
      '8 standard class credits per month',
      'Specialty events and workshops excluded',
      'Unique promo code for 15% off Rhyze merchandise',
      'Credits do not roll over',
    ],
    href: '/join?plan=full-rhythm',
  },
  {
    id: 'eight-class-pack',
    name: '8-Class Pack',
    price: '$179',
    cadence: '/ 3 months',
    eyebrow: '8 classes / 3 months',
    popular: false,
    credits: '8 standard class credits valid for 3 months',
    blurb:
      'A flexible lower-pressure pack for members who want 2–3 classes per month without buying unlimited. Auto-renews every 3 months unless cancelled at least 14 days before renewal.',
    perks: [
      'Available September 1, 2026',
      '8 standard class credits',
      'Class-pack credits expire each 3-month period',
    ],
    details: [
      '8 standard class credits valid for 3 months',
      'Auto-renews every 3 months at $179',
      'Cancel at least 14 days before renewal',
      'Unused credits expire at the end of each 3-month period',
      'RHYZE2026 does not apply to class packs',
    ],
    href: '/join?plan=eight-class-pack',
  },
  {
    id: 'elevate',
    name: 'Elevate',
    price: '$92',
    cadence: '/ month',
    eyebrow: '4 classes / month',
    popular: false,
    credits: '4 monthly standard class credits',
    blurb:
      'A steady once-a-week membership with a unique 10% merch promo code for building consistency across dance, yoga, Pilates, strength, and HIIT.',
    perks: [
      '10% member merch promo code',
      'Monthly credits',
      'Membership terms required',
    ],
    details: [
      'Billing begins August 3, 2026 for opening month',
      '4 standard class credits per month',
      'Specialty events and workshops excluded',
      'Unique promo code for 10% off Rhyze merchandise',
      'Best for once-a-week movers',
    ],
    href: '/join?plan=elevate',
  },
  {
    id: 'vip-access-pass',
    name: 'The VIP Access Pass',
    price: '$222',
    cadence: '/ month',
    eyebrow: 'VIP unlimited',
    popular: false,
    credits: 'Unlimited standard classes plus 1 specialty class monthly',
    blurb:
      'Unlimited standard classes, specialty class access, and a unique 20% merch promo code. New membership buyers can use RHYZE2026 September 1–7 for 20% off the first 2 months.',
    perks: [
      '20% member merch promo code',
      '1 specialty class monthly',
      'RHYZE2026 eligible for new membership buyers',
    ],
    details: [
      'Regular VIP rate starts September 1, 2026',
      'Unlimited standard classes',
      '1 eligible specialty event per month',
      'RHYZE2026 gives 20% off first 2 months only for eligible new membership buyers',
      'Monthly eligible event list; not all events included',
      'Unique promo code for 20% off Rhyze merchandise',
    ],
    href: '/join?plan=vip-access-pass',
  },
] as const;

export const ownedEvents = [
  {
    id: 'tcj-hip-hop-happy-hour-tricia',
    slug: 'tcj-hip-hop-happy-hour-tricia',
    name: 'TCJ Hip-Hop Happy Hour with Tricia',
    instructor: 'Tricia',
    date: 'Aug 3',
    fullDate: 'Monday, August 3rd, 2026',
    time: '7:15 PM',
    duration: '75 min',
    price: '$30',
    capacity: 25,
    booked: 11,
    waitlist: 0,
    photo: '/founders/instructor-tricia.jpg',
    category: 'Special event',
    eligibleForVip: true,
    description:
      'A beginner-friendly hip-hop experience that feels more like a night out than a workout.',
    bullets: [
      'Step-by-step hip-hop or pop routine',
      'Different track and choreography each session',
      'Beginner-friendly; no experience needed',
      'VIP eligible when selected for the monthly specialty list',
    ],
    bookingHref: '/book/event/tcj-hip-hop-happy-hour-tricia',
  },
  {
    id: 'hypnotic-heels-nicole',
    slug: 'hypnotic-heels-nicole',
    name: 'Hypnotic Heels with Nicole',
    instructor: 'Nicole Finley',
    date: 'Aug 10',
    fullDate: 'Monday, August 10th, 2026',
    time: '6:45 PM',
    duration: '75 min',
    price: '$30',
    capacity: 25,
    booked: 1,
    waitlist: 0,
    photo: '/founders/instructor-nicole-finley.png',
    category: 'Special event',
    eligibleForVip: true,
    description:
      'A specialty heels class for confidence, poise, technique, and flow.',
    bullets: [
      'Warm-up, posture, balance, strutting, and choreography',
      'Fresh monthly theme with optional video runs',
      'Bring sturdy heels with ankle support and knee pads',
      'VIP eligible when selected for the monthly specialty list',
    ],
    bookingHref: '/book/event/hypnotic-heels-nicole',
  },
  {
    id: 'seat-seduction-vanessa',
    slug: 'seat-seduction-vanessa',
    name: 'Seat Seduction With Vanessa',
    instructor: 'Vanessa Ramos',
    date: 'Aug 21',
    fullDate: 'Friday, August 21st, 2026',
    time: '6:45 PM',
    duration: '75 min',
    price: '$30',
    capacity: 25,
    booked: 0,
    waitlist: 0,
    photo: '/founders/instructor-vanessa.jpg',
    category: 'Special event',
    eligibleForVip: false,
    description:
      'A Friday night chair choreography class for confidence, flow, and self-expression.',
    bullets: [
      'Beginner-friendly chair choreography',
      'Step-by-step movement with room to let go',
      'Wear comfortable clothes that makes you feel good, socks (or barefoot), and knee pads.',
    ],
    bookingHref: '/book/event/seat-seduction-vanessa',
  },
] as const;

export const studioSignups = [
  {
    name: 'Ava Martinez',
    email: 'ava.martinez@example.com',
    phone: '(973) 555-0112',
    address: '14 Maple Lane, Sparta, NJ',
    source: '$7 Intro Offer',
    purchase: 'Intro Offer 7-Days',
    startDate: 'Aug 3, 2026',
    activity: 'Rhyze Up booked; waiver pending',
  },
  {
    name: 'Priya Santos',
    email: 'priya.santos@example.com',
    phone: '(862) 555-0144',
    address: '88 Main Street, Lafayette, NJ',
    source: 'Membership checkout',
    purchase: 'Ritual membership',
    startDate: 'Aug 2, 2026',
    activity: '2 classes booked; waiver signed',
  },
  {
    name: 'Jordan Lee',
    email: 'jordan.lee@example.com',
    phone: '(201) 555-0198',
    address: '22 Lakeview Drive, Newton, NJ',
    source: 'Single class',
    purchase: 'Pilates Pulse drop-in',
    startDate: 'Aug 2, 2026',
    activity: 'First class booked',
  },
  {
    name: 'Camila Reyes',
    email: 'camila.reyes@example.com',
    phone: '(973) 555-0167',
    address: '7 Summit Road, Andover, NJ',
    source: 'Newsletter',
    purchase: 'Email updates only',
    startDate: 'Aug 3, 2026',
    activity: 'No purchase yet; opening updates list',
  },
  {
    name: 'Nina Patel',
    email: 'nina.patel@example.com',
    phone: '(908) 555-0123',
    address: '31 Spring Court, Branchville, NJ',
    source: 'VIP checkout',
    purchase: 'VIP Access Pass',
    startDate: 'Aug 3, 2026',
    activity: 'Active member; specialty eligible',
  },
] as const;

export const getOwnedEvent = (slug: string) =>
  ownedEvents.find((event) => event.slug === slug);

export const dropInOffers = [
  {
    id: 'drop-in',
    name: 'Single Class Drop-In',
    price: '$25',
    detail: 'One standard class, no membership needed',
  },
  {
    id: 'specialty',
    name: 'Specialty Workshop',
    price: '$30',
    detail: 'Heels, chair choreography, workshops, and limited events',
  },
] as const;

export const studioMetrics = [
  { label: "Today's income", value: '$1,842', detail: '+18% vs last Tuesday' },
  {
    label: 'Monthly recurring',
    value: '$14,916',
    detail: '127 active memberships',
  },
  {
    label: 'Bookings this week',
    value: '184',
    detail: '86% average attendance',
  },
  {
    label: 'Waivers needed',
    value: '7',
    detail: '3 guardian signatures pending',
  },
] as const;

export const customerPortal = {
  memberName: 'Maya Collins',
  membership: 'Ritual',
  creditsLeft: 5,
  waiverStatus: 'Signed',
  nextClass: ownedSchedule[0],
  attendanceHistory: [
    { date: 'Jul 18', className: 'Rhyze Ritmo', status: 'Attended' },
    { date: 'Jul 15', className: 'Pilates Pulse', status: 'Attended' },
    { date: 'Jul 11', className: 'Rhyze Up', status: 'Attended' },
    { date: 'Jul 08', className: 'Ignite', status: 'Missed' },
  ],
  recommendations: [
    {
      slug: 'rhyze-up-vanessa',
      name: 'Rhyze Up with Vanessa',
      category: 'dance',
      duration: 50,
      description: 'Rhythm-driven dance fitness with Vanessa',
      href: '/book/rhyze-up-vanessa',
    },
    {
      slug: 'rhyze-ritmo-melissa',
      name: 'Rhyze Ritmo with Melissa',
      category: 'dance',
      duration: 50,
      description: 'Latin rhythms and full-body cardio with Melissa',
      href: '/book/rhyze-ritmo-melissa',
    },
    {
      slug: 'pilates-pulse-adrianna',
      name: 'Pilates Pulse with Adrianna',
      category: 'yoga',
      duration: 50,
      description: 'Functional flow, strength, stability, and mobility',
      href: '/book/pilates-pulse-adrianna',
    },
  ],
} as const;

export const adminQueues = [
  '7 customers need waiver follow-up',
  '3 failed membership payments need review',
  'Hypnotic Heels has 6 people on the waitlist',
  '12 members have not attended in 21 days',
] as const;

export const automations = [
  'Welcome email after account creation',
  'Booking confirmation',
  '24-hour class reminder',
  'Waiver reminder',
  'Inactive member win-back',
] as const;
